sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

env:
  - XQA_CONTAINER=xqa-db

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - docker-compose -p "dev" up -d
  - sleep 10
  - docker exec $XQA_CONTAINER pg_dump -U xqa -s xqa > schema.sql
  - diff schema.sql schema/schema.sql
