version: '3'

services:
  xqa-db:
    build: .
    image: xqa-db
    container_name: xqa-db
    volumes:
      - "xqa-db:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - xqa

volumes:
  xqa-db:

networks:
  xqa:
